<a href="https://colab.research.google.com/github/wScouse/wscouse.github.io/blob/master/HelloWorld.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Overview
TensorFlow 2 quickstart for beginners.
[Tutorial](https://www.tensorflow.org/tutorials/quickstart/beginner)

In [2]:
import tensorflow as tf
print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.9.2


Load and prepare the MNIST dataset.

In [3]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


Build a machine learning model

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.3284515 , -0.3486528 ,  0.14088455, -0.00651929,  0.07514873,
         0.10884321, -0.41233936, -0.24714233, -0.08720793,  0.13578162]],
      dtype=float32)

Convert logits to probabilities for each class.

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.13975748, 0.07100883, 0.11585526, 0.09997677, 0.10848434,
        0.11220195, 0.06662753, 0.07859553, 0.09222665, 0.11526557]],
      dtype=float32)

Define a loss function

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

Loss function

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.1874547

Configure and compile model

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

# Train and Evaluate Model

Train model

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2938 - accuracy: 0.9145
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1417 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1064 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0873 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0751 - accuracy: 0.9766


Evaluate model

In [12]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0766 - accuracy: 0.9763 - 419ms/epoch - 1ms/step


[0.07655389606952667, 0.9763000011444092]

Return a probability

In [13]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.60593074e-08, 2.34632026e-07, 5.46210540e-05, 3.09882889e-04,
        4.19380780e-11, 7.94855907e-07, 2.89262754e-13, 9.99580443e-01,
        8.43074986e-07, 5.29835743e-05],
       [1.88040499e-08, 3.58943580e-05, 9.99958515e-01, 5.06083643e-06,
        1.07172663e-16, 4.57021656e-07, 4.32572094e-08, 5.77434212e-11,
        1.11524741e-07, 7.07425983e-16],
       [2.58405237e-07, 9.98715878e-01, 2.54548184e-04, 1.80542920e-05,
        5.53887839e-05, 1.56301885e-05, 6.85717350e-06, 7.81999202e-04,
        1.50567634e-04, 8.66685298e-07],
       [9.99881268e-01, 2.52636696e-11, 1.49241587e-05, 2.66790607e-08,
        4.70855213e-08, 4.93732898e-07, 7.92747232e-05, 1.80225328e-07,
        8.32897307e-09, 2.38285265e-05],
       [7.31366163e-06, 4.45629134e-08, 6.28485213e-06, 3.59841067e-07,
        9.99028802e-01, 4.88341084e-06, 3.61634811e-05, 4.12561421e-05,
        4.90811203e-07, 8.74504331e-04]], dtype=float32)>